### PR TITLE
Non-interactive Header elements announced by some screen readers with "Double tap to activate"

### PR DESCRIPTION
**Pull request by kopijunkie**
# Problem
On Android mobiles, Talkback screen reader is announcing the SDK's header elements with an additional "Double tap to activate" instruction despite them being non-interactive elements.

# Solution
Separate ARIA role for heading element in PageTitle component from `tabIndex="-1"` setting.

`tabIndex="-1"` is needed to remove element from tab order and allow for programmatically resetting screen reader focus on new screen render. But there is an issue where Android Talkback thinks any header element that has a `tabindex` of 0 or -1 is automatically an interactive element. See StackOverflow issue [here](https://stackoverflow.com/questions/42424170/talk-back-announce-double-tap-to-activate-on-header-element)

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [x] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [ ] Have new automated tests been implemented?
- [ ] Have new manual tests been written down?
- [n/a] Have any new strings been translated?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by kopijunkie** [comment]
> looks like all the headings are fixed apart from the one on the welcome page. Upon opening the link on the pixel3, screenreader still reads out "Open your new bank account" twice with "double check to activate"? Is that because it is a different heading to the rest?

That's an odd one. That heading on Welcome screen is the same PageTitle component as the other screens actually. Will take a look when I'm back in.

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-804-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://804-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
