### PR TITLE
Fix vulnerabilities in development

### PR DESCRIPTION
**Pull request by stefaniacardenas**
# Problem
`npm audit` detected some moderate vulnerabilities on `development` branch

# Solution
Fix vulnerabilities by running `npm audit fix`

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [x] Has the CHANGELOG been updated?
- [ ] Has the README been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [ ] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-951-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-951-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-951-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-951-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by stefaniacardenas** [comment]
I think it's good to know at which point we introduced a change. It will be helpful in case there is a bug that we need to traceback

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-951-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-951-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://951-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
