### PR TITLE
Post release/merge 5.11.1 into development

### PR DESCRIPTION
**Pull request by eraxyz**
Merge release 5.11.1 changes back into development

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1065-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1065-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1065-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by bartzet** [comment]
Hmmm... if it was a hotfix branched off of master, this PR should include the hotfix change itself, shouldn't it?

**Comment by kopijunkie** [comment]
> Hmmm... if it was a hotfix branched off of master, this PR should include the hotfix change itself, shouldn't it?

In this case, the fix itself was already in `development` but had to be cherry picked into the hotfix branched off of `master`. So any diffs would be in the `CHANGELOG`, `package.json`, etc.

**Comment by bartzet** [comment]
Gottcha, I wasn't aware fix was in development already :)

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1065-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1065-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1065-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
