### PR TITLE
Release/0.15.0

### PR DESCRIPTION
**Pull request by dawiddylowicz**
### Changed
- Internal: Use HTTP protocol to post documents to the server instead of websockets

### Fixed
- Public: Fixed intermittent connection problem

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://151-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by hjheath** [comment]
Don't forget to update the links in the Changelog - line 186

**Comment by rfreitas** [comment]
Travis automatic deployment: https://151-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://151-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://151-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
