### PR TITLE
Post release/merge 5 7 1 into development

### PR DESCRIPTION
**Pull request by kopijunkie**
# Task
Merge `master` including `5.7.1` release into `development`

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-924-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-924-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://924-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by joninvski** [comment]
Commits: 
9db99b5  and  fda5837 should be squashed

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-924-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-924-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://924-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-924-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-924-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-924-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-924-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://924-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://924-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
