### PR TITLE
Feature/add option for initial cross device delivery option

### PR DESCRIPTION
**Pull request by ctrlaltdylan**
# Problem

The initial cross device URL delivery option is not configurable. It's hardcoded to the `qr_code` option:

Screen Shot 2020-01-24 at 12 56 30 PM

Not every demographic using this UI will favor a QR code. Our use case needs SMS as the first option to reduce friction.

# Solution

Add a configurable option in the `documents` step called `initialCrossDeviceDeliveryOption` which allows the implementer to decide which delivery method they'd like to have presented first.

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [Y] Has the CHANGELOG been updated?
- [Y] Has the README been updated?
- [N] Has the RELEASE_GUIDELINES been updated?
- [N] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [N] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [N] Have any new automated tests been implemented or the existing ones changed?
- [N] Have any new manual tests been written down or the existing ones changed?
- [N] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Comment by stefaniacardenas** [comment]
Hi @ctrlaltdylan, thanks for raising this PR. I will discuss this feature request with the team before merging it. Again, thank you so much for thanking the time to contribute. Feel free to get in touch if you have any other feedback or suggestion.

**Comment by ctrlaltdylan** [comment]
@stefaniacardenas just wanted to ping you, we've deployed our fork to production. 

We would much appreciate an update if there are plans to merge in this change or if your team wants to go in a different direction.

We'd like to stay up to date with your changes, but ideally not maintain a fork in the long run.

**Comment by stefaniacardenas** [comment]
Hi @ctrlaltdylan, we are planning to merge this PR next sprint and do some additional work on it. I will let you know when this change will go live but I reckon it will be next release or the one after. Thank you for your patience.

**Comment by ctrlaltdylan** [comment]
@stefaniacardenas not a problem, thanks for the update 👍

**Comment by HuntCol** [comment]
+1 for this!

**Comment by bartzet** [comment]
We have merged the fix for this today.

It will be included in our next release.

**Comment by ctrlaltdylan** [comment]
@stefaniacardenas could this be reviewed/fixed/merged so it can be a part of the release for fixing IE?

Once again we'll be forced to update our fork because of a bug from selfie capture issues.

**Comment by stefaniacardenas** [comment]
Hi @ctrlaltdylan, sorry for delay on this one. We are evaluating this change as a possible mid-term feature, as there are a few business implications that we need to consider before introducing this change. I will close this PR for now but you can still discuss your use case with your account manager if you consider this a critical feature.

**Pull request closed without merging**
