### PR TITLE
Update link to Web SDK documentation

### PR DESCRIPTION
**Pull request by bahmady**
# Problem
We're about to change a link on documentation.onfido.com

# Solution
This ensures this README won't be left with a broken link

## Checklist
n/a

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-610-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-610-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://610-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by bartzet** [comment]
I'm not sure we should be merging directly to `master`. What's your thought @stefaniacardenas?

**Comment by bahmady** [comment]
In hindsight there are actually a few other broken links in the README(s) now. I can fix all of these today but would be good to get an idea of how best to do this.

**Comment by bartzet** [comment]
Definitely through the pull request. My only concern is that we don't tend to merge anything to `master` branch directly but rather to the `development` branch so these fixes will be applied with our next release.

**Comment by rfreitas** [comment]
if we do want to hotfix the master, then that change needs to be merged to development too.

**Comment by bahmady** [comment]
No worries, I'm happy to open a PR against `development` but since there are other broken links, it would probably make sense to do it all in one PR, so I can amend this one or open a new one.

**Pull request closed without merging**
