### PR TITLE
Feature/file size limit cx449

### PR DESCRIPTION
**Pull request by hjheath**

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://137-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
@hjheath conflicts on this one

**Comment by rfreitas** [comment]
Travis automatic deployment: https://137-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by hjheath** [comment]
I resolved the conflicts

**Pull request merged**
