### PR TITLE
Remove unused imports and track them with eslint

### PR DESCRIPTION
**Pull request by hjheath**

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://195-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-195-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by hjheath** [comment]
@rfreitas could you look at this - do you want to include it in your PR to remove old code?

**Comment by rfreitas** [comment]
fine to include it, please merge it if it's running okay on your side

**Comment by rfreitas** [comment]
Travis automatic deployment: https://195-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-195-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
