### PR TITLE
Uses different descripe scopes per check

### PR DESCRIPTION
**Pull request by joninvski**
# Problem
Use describe blocks for each one of checks of a page

# Solution

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [ ] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [ ] Have new automated tests been implemented?
- [ ] Have new manual tests been written down?
- [ ] Have tests passed locally?
- [ ] Have any new strings been translated?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-638-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-638-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://638-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by joninvski** [comment]
@bartzet seems to be working:

image

Do you want to include this in your PR?

I think having small describe blocks will help structuring the specs.

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-638-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-638-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://638-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
