### PR TITLE
Update monster gem dependency in cucumber tests

### PR DESCRIPTION
**Pull request by dawiddylowicz**
This is required due the most recent breaking changes introduced on master in `monster` gem, one of cucumber test dependencies.

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-239-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-239-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-239-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://239-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by dawiddylowicz** [comment]
Tests passed, merging

**Pull request merged**
