### PR TITLE
Sync development and prerelease to include changes

### PR DESCRIPTION
**Pull request by stefaniacardenas**
Merging the work within this PR #394 into `development`

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-395-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-395-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-395-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-395-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://395-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://395-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by stefaniacardenas** [comment]
Closed this PR as the code has already been reviewed within #394 so I just cherry-picked those two commits into `development`.

**Pull request closed without merging**
