### PR TITLE
Feature/et 821 Add applicantId to the configuration object

### PR DESCRIPTION
**Pull request by eraxyz**
# Problem

In order to use the new decoupling/customized API feature, integrators may need to know the applicant_id of the end-user submitting the data.  

# Solution

Added a place for integrators to add the applicant_id as applicantId within the enterpriseFeatures configuration. This will then be added to the callbacks if present.

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [x] Has the CHANGELOG been updated?
- [ ] Has the README been updated?
- [ ] Has the CONTRIBUTING doc been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [x] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1350-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1350-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1350-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1350-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1350-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1350-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1350-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1350-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1350-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by ethan605** [comment]
I feel a bit unconvinced about this PR:

1. We've kept `applicant_id` our of the SDK scope for a while, and it's still working fine. I think this is a good practice because the SDK doesn't know much about unrelated data.
2. Because the integrator would customise the API callbacks to handle the image uploading, I think they have enough context (`applicant_id` in this case obviously, but maybe there're other ones). I don't think it's necessary to pass the ID into the configuration.
3. There're no changes in the code reflecting that we need `applicant_id` inside the SDK.
4. Even if the `applicant_id` is necessary, I don't think that placing `applicant_id` deep in the configuration instead of the top-level (like `token` or `containerId`) is a good idea. It increases the complexity of configuration validation and traversal.

**Comment by eraxyz** [comment]
> I feel a bit unconvinced about this PR:
> 
> 1. We've kept `applicant_id` our of the SDK scope for a while, and it's still working fine. I think this is a good practice because the SDK doesn't know much about unrelated data.
> 2. Because the integrator would customise the API callbacks to handle the image uploading, I think they have enough context (`applicant_id` in this case obviously, but maybe there're other ones). I don't think it's necessary to pass the ID into the configuration.
> 3. There're no changes in the code reflecting that we need `applicant_id` inside the SDK.
> 4. Even if the `applicant_id` is necessary, I don't think that placing `applicant_id` deep in the configuration instead of the top-level (like `token` or `containerId`) is a good idea. It increases the complexity of configuration validation and traversal.

Thanks for the feedback, Ethan. I actually feel the same way. The reason for this change was stronger with the previous solution proposed for network decoupling but the only argument for it now could be that it makes integration slightly easier. I've talked to my team and convinced them this is not needed so I will be closing this PR. Thanks again.

**Pull request closed without merging**
