### PR TITLE
Fix/camera permission screen icon background colour mismatch

### PR DESCRIPTION
**Pull request by kopijunkie**
# Problem
The camera permission screen's icon has a white `#FFFFFF` background colour set in the screen's style sheet. In PR #1290 the SDK's background was changed to an off-white colour `#FCFCFD`
Screenshot of CameraPermission screen on desktop browser Screenshot of CameraPermission screen on mobile browser

# Solution
Make the background colour transparent as background colour could be changed to something else again in the future.

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [n/a] Has the CHANGELOG been updated? _(dev regression in unreleased feature)_
- [ ] Has the README been updated?
- [ ] Has the CONTRIBUTING doc been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [ ] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Review by ethan605 — APPROVED** [review]
Super quick spot! Thanks for this

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1317-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1317-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1317-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1317-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1317-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1317-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
