### PR TITLE
Chromedriver via npm, remove scripts

### PR DESCRIPTION
**Pull request by bartzet**
# Problem

# Solution

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [ ] Has the CHANGELOG been updated?
- [ ] Has the README been updated?
- [ ] Has the CONTRIBUTING doc been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [ ] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1109-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1109-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1109-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by bartzet** [comment]
```Error executing chrome test case { SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 83
    at Object.throwDecodedError (/home/travis/build/onfido/onfido-sdk-ui/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/home/travis/build/onfido/onfido-sdk-ui/node_modules/selenium-webdriver/lib/http.js:565:13)
    at Executor.execute (/home/travis/build/onfido/onfido-sdk-ui/node_modules/selenium-webdriver/lib/http.js:491:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'SessionNotCreatedError',
  remoteStacktrace: '#0 0x55ffe9cda579 <unknown>\n' }
Finished test```

**Pull request closed without merging**
