### PR TITLE
Force React to create a new element instead of recyling it

### PR DESCRIPTION
**Pull request by elhesuu**
# Problem
User should not temporarily see the image from the previous confirmation screen when confirming a face upload.

Acceptance criteria:
- user should see the same transition as the doc upload (i.e. the 1st confirmation screen) when they are confirming their face upload
- same should be applied to both webcam and upload

# Solution
Set `capture.id` as the `img` element key, in order to prevent React from recycling it.

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [n/a] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [n/a] Have new automated tests been implemented?
- [n/a] Have new manual tests been written down?
- [ ] Have tests passed locally?
- [n/a] Have any new strings been translated?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-482-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-482-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-482-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-482-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-482-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-482-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://482-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by seewah** [comment]
functionality-wise, changes look good. thanks @elhesuu

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-482-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
