### PR TITLE
Inconsistent font style for Back button, Upload link button from rest of SDK

### PR DESCRIPTION
**Pull request by kopijunkie**
# Problem
We have inconsistent font style for the Back button, Upload link button when compared to the rest of the SDK.

Upload Document button, Copy Link button, Back button are using Arial font instead of the usual `"Open Sans", sans-serif` font family throughout the SDK.

# Solution
Defined a common font family Sass variable to be reused wherever font family needs to be defined. This includes setting it for a button element as the browser default is applied instead if not set.

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [x] Has the CHANGELOG been updated?
- [ ] Has the README been updated?
- [ ] Has the CONTRIBUTING doc been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [ ] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1184-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1184-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1184-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1184-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1184-pr-onfido-sdk-ui-onfido.surge.sh

**Review by josokinas — APPROVED** [review]

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1184-pr-onfido-sdk-ui-onfido.surge.sh

**Review by ethan605 — APPROVED** [review]

**Pull request merged**
