### PR TITLE
Feature/error consistency cx 2352 icons

### PR DESCRIPTION
**Pull request by elhesuu**
# Problem
After updates to icons, the same icon should be used for all viewports

# Solution
Remove larger version, and keep a single version of error and warning icons

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [n/a] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [n/a] Have new automated tests been implemented?
- [n/a] Have new manual tests been written down?
- [n/a] Have tests passed locally?
- [n/a] Have any new strings been translated?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-412-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-412-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://412-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by danielspagnolo** [comment]
This looks right now 👍
Thanks

**Pull request merged**
