### PR TITLE
Improvement/cx 6285 readme updates

### PR DESCRIPTION
**Pull request by seewah**
# Problem
recommendation after internal review needs to be actioned on
# Solution

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [n/a] Has the CHANGELOG been updated?
- [x] Has the README been updated?
- [n/a] Has the CONTRIBUTING doc been updated?
- [n/a] Has the RELEASE_GUIDELINES been updated?
- [n/a] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [n/a] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [n/a] Have any new automated tests been implemented or the existing ones changed?
- [n/a] Have any new manual tests been written down or the existing ones changed?
- [n/a] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Review by stefaniacardenas — APPROVED** [review]
LGTM. As this is just a readme change I suggest we should merge this into the release branch if @kopijunkie agrees.

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1386-pr-onfido-sdk-ui-onfido.surge.sh

**Review by kopijunkie — APPROVED** [review]

**Review by ethan605 — APPROVED** [review]

**Comment by kopijunkie** [comment]
> LGTM. As this is just a readme change I suggest we should merge this into the release branch if @kopijunkie agrees.

Yes. We should be find to merge this into the release branch. :)

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1386-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1386-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
