### PR TITLE
Avoid specifying document type

### PR DESCRIPTION
**Pull request by elhesuu**
# Problem
User should see "photos" instead of "ID photos" on the cross-device intro screen for both the "document" and "poa" steps - so just have one version which says "photos"

# Solution
Remove `ID` from `ID photos`.
Also, I found some unused strings which I removed

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [n/a] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [n/a] Have new automated tests been implemented?
- [n/a] Have new manual tests been written down?
- [n/a] Have tests passed locally?
- [n/a] Have any new strings been translated?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-433-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-433-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://433-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by seewah** [comment]
please resolve conflict @elhesuu thanks

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-433-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-433-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-433-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-433-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-433-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-433-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://433-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
