### PR TITLE
Fix/cx 3913 Front side of previously uploaded 2-sided doc visible in PoA upload step

### PR DESCRIPTION
**Pull request by kopijunkie**
# Problem
Some clients want to set up the SDK with PoA step ordered after Document Capture step. 

If a user selects a 2-sided ID Document after both sides are uploaded and the user moves on to the PoA step, after the PoA Document Select view they are taken straight to the PoA Confirm view but with the front side of the earlier uploaded document instead. If they were to click on the Back button, this would go back to the PoA Capture view they were originally expecting.

The SDK was skipping ahead by 2 views  whenever it had to deal with compensating for additional Back Document Capture views when a user selects a 2-sided document. 

# Solution
`StepComponentMap` builds out the capture steps quite early on and updates when a 2-sided document is selected. Additionally it treats Capture and Confirm as 2 separate steps. 
Changed this behaviour to have Capture and Confirm view decided by a `DocumentCaptureFlow` controller. 

Moving back a step/view is determined by listening for a `backToPreviousView` event on these views and what to display is decided by `currentView` state.

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [x] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [ ] Have new automated tests been implemented?
- [ ] Have new manual tests been written down?
- [x] Have tests passed locally?
- [n/a] Have any new strings been translated?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-772-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-772-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://772-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-772-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-772-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://772-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by kopijunkie** [comment]
Closed as the implementation needs a rethink.

**Pull request closed without merging**
