### PR TITLE
Add support for Peru residence permit

### PR DESCRIPTION
**Pull request by kopijunkie**
# Problem
Onfido have started supporting Peru Residence Permit as of 19 October 2020 so the Web SDK needs to be updated to include Peru as an option for users on the Country Selection screen when Residence Permit is selected.

# Solution
Get latest supported documents data from Docupedia.

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [x] Has the CHANGELOG been updated?
- [ ] Has the README been updated?
- [ ] Has the CONTRIBUTING doc been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [ ] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1229-pr-onfido-sdk-ui-onfido.surge.sh

**Review by anuragajwani — APPROVED** [review]

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Review by ethan605 — APPROVED** [review]
LGTM in general. Just one question: why it produces big diffs with JSON files? Can we avoid it in the future tickets relating to adding new document support?

**Comment by kopijunkie** [comment]
> LGTM in general. Just one question: why it produces big diffs with JSON files? Can we avoid it in the future tickets relating to adding new document support?

I think it's because the JSON's data is not sorted on export. I've changed that since so the JSON files from this PR onwards will always be sorted by country name on export.

**Review by seewah — CHANGES_REQUESTED** [review]
Saudi ID card seems to be missing from the list now. Is that intentional? please confirm with doc team, and maybe add that to the changelog too if it is indeed correct

**Comment by seewah** [comment]
and columbia RP is needed too?

**Comment by kopijunkie** [comment]
> and columbia RP is added too?

Have confirmed with the Documents team that these changes are correct. Will update the `CHANGELOG`.

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1229-pr-onfido-sdk-ui-onfido.surge.sh

**Review by seewah — APPROVED** [review]

**Pull request merged**
