### PR TITLE
Chore/update contributing doc

### PR DESCRIPTION
**Pull request by kopijunkie**
# Problem
We use the Lokalise CLI ver2 tool to download copy updates from Lokalise. While the tool itself is run via an npm command in project's `package.json`, this is not a npm package so contributors might not know how to install it.

# Solution
Include information about this tool in `CONTRIBUTING.md` doc and link to the CLI tool's repo which has details on how to install it depending on OS.

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [x] Has the CHANGELOG been updated?
- [ ] Has the README been updated?
- [x] Has the CONTRIBUTING doc been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [ ] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1395-pr-onfido-sdk-ui-onfido.surge.sh

**Review by stefaniacardenas — APPROVED** [review]

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1395-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1395-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1395-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
