### PR TITLE
Fix/release script

### PR DESCRIPTION
**Pull request by ethan605**
# Problem

The release script (`./release/release.js`) didn't work properly on:
- Update `BASE_32_VERSION`
- Publishing tag

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [x] Has the CHANGELOG been updated?
- [n/a] Has the README been updated?
- [n/a] Has the CONTRIBUTING doc been updated?
- [n/a] Has the RELEASE_GUIDELINES been updated?
- [n/a] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [n/a] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [n/a] Have any new automated tests been implemented or the existing ones changed?
- [n/a] Have any new manual tests been written down or the existing ones changed?
- [n/a] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1216-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1216-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1216-pr-onfido-sdk-ui-onfido.surge.sh

**Review by kopijunkie — APPROVED** [review]
LGTM

**Review by stefaniacardenas — APPROVED** [review]
This looks good to me. I think we should add a mapping of all the current base32 version and the semver equivalent, so that every time the script creates a new base 32 version, we can check if it already exist. I can create that mapping, we can create another ticket to use the mapping in the release script

**Comment by ethan605** [comment]
> This looks good to me. I think we should add a mapping of all the current base32 version and the semver equivalent, so that every time the script creates a new base 32 version, we can check if it already exist. I can create that mapping, we can create another ticket to use the mapping in the release script

That's a good idea!

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1216-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1216-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1216-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
