### PR TITLE
Release/6.1.0

### PR DESCRIPTION
**Pull request by ethan605**
# Changelog

### Added

- Public: Add `migrate_locales` script to enable integrator migrate to next versions of Web SDK locale system.
- Internal: Add `unwrap_lokalise` script to sanitise locale files pulled from Lokalise.

### Changed

- Public: Introduced new system for locale keys. Keys are now more structured and easier to find within the code.
- Internal: Replace all string values from `JS SDK` to `Web SDK` and `js-sdk` to `web-sdk`.

### Fixed

- UI: Accessibility - Error and warning alert heading is now ARIA heading level 1
- UI: Camera inactivity timeout only starts from camera access granted instead of on initial render
- UI: Fixed call to action buttons covering content and instructions on Passport Image Guide, Selfie Intro screens when viewed on a mobile device with a shorter viewport, e.g. iPhone SE (1st gen)

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1219-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1219-pr-onfido-sdk-ui-onfido.surge.sh

**Review by stefaniacardenas — APPROVED** [review]
🚀

**Review by kopijunkie — APPROVED** [review]

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1219-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
