### PR TITLE
Feature/0.12.0 rc

### PR DESCRIPTION
**Pull request by hjheath**
Tested with Travis - I will update the RC tag to point at this when merged

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://117-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
so what is the update on this?

**Comment by hjheath** [comment]
It's good to go! Once I merge I will point the 0.12.0-rc.1 tag at this merge commit

**Comment by rfreitas** [comment]
we should still open an issue to deploy with travis release candidates as well

**Pull request merged**
