### PR TITLE
Raise file size limit to 10 MB

### PR DESCRIPTION
**Pull request by hjheath**
Given we now resize images on platform we can raise the file size limit to match the limit on the API.

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://157-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://157-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Changelog change missing.

**Comment by rfreitas** [comment]
Travis automatic deployment: https://157-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
has the limit already been raised on the api? Otherwise this cannot be released?

**Comment by hjheath** [comment]
The limit will be raised on the next release - due out on Monday

**Comment by rfreitas** [comment]
I would hold until then before pushing this to development.

**Pull request merged**
