### PR TITLE
Fix Document Selector UI

### PR DESCRIPTION
**Pull request by stefaniacardenas**
# Problem
The content of document selector options is overflowing it's container. See screenshot below
screen shot 2019-02-22 at 10 14 37

# Solution
Added `flex-shrink: 0` to the parent component.
Result:
screen shot 2019-02-22 at 10 15 28
Added Manual regressions testing steps. I created a ticket to implement automated tests

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [ ] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [ ] Have new automated tests been implemented?
- [ ] Have new manual tests been written down?
- [x] Have tests passed locally?
- [ ] Have any new strings been translated?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-588-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-588-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://588-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-588-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://588-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-588-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-588-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-588-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://588-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by bartzet** [comment]
How the alignment of the icons is set up? Do we center them in the container or do we place them with the even distance from the upper edge of the container?

image

**Comment by stefaniacardenas** [comment]
They have a margin top. They are not centered. See latest below (second box)
screen shot 2019-02-26 at 11 14 46

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-588-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://588-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-588-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
it's quite weird that this change added 2% to the bundle size...

**Pull request merged**
