### PR TITLE
Fix large CSS file size

### PR DESCRIPTION
**Pull request by kopijunkie**
# Problem
The `styles.css` file in our builds has now increased to 5MB, which is significantly bigger than the minimised JS file. File size increase was due to the 4 document example SVGs added for Passport Guide screen.

# Solution
Since the document examples are more complex photographic images and not the usual simple icon elements images, Figma assets should be exported as raster images instead of vector images.

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [n/a] Has the CHANGELOG been updated? (unreleased feature)
- [n/a] Has the README been updated?
- [n/a] Has the CONTRIBUTING doc been updated?
- [n/a] Has the RELEASE_GUIDELINES been updated?
- [n/a] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [n/a] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [n/a] Have any new automated tests been implemented or the existing ones changed?
- [n/a] Have any new manual tests been written down or the existing ones changed?
- [n/a] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1054-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1054-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1054-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1054-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1054-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1054-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1054-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by joninvski** [comment]
Small note. If you want to reduce a little bit more (not really significant) you can use `optipng`

image

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1054-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1054-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
