### PR TITLE
Chore/Bump chromedriver & update lib/index.d.ts

### PR DESCRIPTION
**Pull request by ethan605**
# Problem

# Solution

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [n/a] Has the CHANGELOG been updated?
- [n/a] Has the README been updated?
- [n/a] Has the CONTRIBUTING doc been updated?
- [n/a] Has the RELEASE_GUIDELINES been updated?
- [n/a] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [n/a] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [n/a] Have any new automated tests been implemented or the existing ones changed?
- [n/a] Have any new manual tests been written down or the existing ones changed?
- [n/a] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1355-pr-onfido-sdk-ui-onfido.surge.sh

**Review by kopijunkie — APPROVED** [review]
LGTM. But suggest updating the PR's description & title since there is a (necessary) addition in `lib/index.d.ts` which is unrelated to the `chromedriver` version.

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1355-pr-onfido-sdk-ui-onfido.surge.sh

**Review by stefaniacardenas — APPROVED** [review]

**Comment by ethan605** [comment]
> LGTM. But suggest updating the PR's description & title since there is a (necessary) addition in `lib/index.d.ts` which is unrelated to the `chromedriver` version.

Thanks, I've updated it.

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1355-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
