### PR TITLE
[CX-1540] Add Pull Request template

### PR DESCRIPTION
**Pull request by dawiddylowicz**
# Problem
Sometimes we go back and forth with PR review due to lacks in documentation, tests and other updates that should initially be part of the PR, instead of focusing on the real problem that PR is solving. This adds additional friction to PR review.

# Solution
Introducing a pull request template with a checklist so that it's easier for PR creator to mind adding all necessary changes before creating a pull request. This should speed up process of PR review.

**Note:** Pull request template will start working once it's merged to default branch (`master` in our case). Hence the PR's destination.

## Checklist
- [n/a] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [n/a] Have new automated tests been implemented?
- [n/a] Have new manual tests been written down?
- [n/a] Have tests passed locally?
- [n/a] Have any new strings been translated?
- [ ] Item to test markdown checkbox

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-289-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-289-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://289-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by hjheath** [comment]
So was the checklist part of the description on this PR auto generated?

**Comment by dawiddylowicz** [comment]
@hjheath Nope, it wasn't autogenerated for this PR because first the file must be on repo default branch, that is `master` in this case. After merging, it should appear on any other PR to this repo.

I was thinking that the cheklist is supposed to be a reminder instead of a hassle for the one who creates a PR. But ticked off checklist may be helpful for the reviewer and acceptor to see if everything is covered

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-289-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-289-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://289-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
