### PR TITLE
Upgraded postcss-url to get rid of handlebars vulnerability

### PR DESCRIPTION
**Pull request by stefaniacardenas**
Updated `postcss-url` as it was using a version of `handlebars` that included a security vulnerability. The latest version of `postcss-url` does not use `handlebars` therefore this solves the issue.

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-265-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://265-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by hjheath** [comment]
Where/how do we use this dependency?

**Comment by stefaniacardenas** [comment]
Every time you write `url(assets/some-image.svg)` it translates the path into data uri into the CSS

**Pull request merged**
