### PR TITLE
Add open sans semibold variant to demo app

### PR DESCRIPTION
**Pull request by elhesuu**
# Problem
Currently semibold is incorrectly referenced in the demo app, and the browser renders a "fake bold" version of the regular variant.

# Solution
Update link tag to point to the correct semibold variant.

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [n/a] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [n/a] Have new automated tests been implemented?
- [n/a] Have new manual tests been written down?
- [n/a] Have tests passed locally?
- [n/a] Have any new strings been translated?

### CODE REVIEW

**Comment by danielspagnolo** [comment]
img_3503

**Comment by elhesuu** [comment]
Thanks @danielspagnolo 

- The back button copy was hidden on small viewports in #434
- It is indeed using "System UI" but it doesn't look like a regression introduced by this PR, and should probably go in a separate ticket?

**Comment by danielspagnolo** [comment]
@elhesuu yep you're right about the back copy on mobile (I forgot)...I'll approve and add system UI ticket to backlog.

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-447-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-447-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://447-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
