### PR TITLE
Fixed: wpt dependency git—>tar.

### LINKED ISSUE #646: [security] 153 known vulnerabilities
Hi, first off let me start by saying thank you for creating this module and the hard work you've clearly put towards it over the years.

I have found that this package have 153 known vulnerabilities (11 unique) just by running `npm install` which runs `npm audit`. So the summary is
```
found 153 vulnerabilities (125 low, 8 moderate, 20 high) in 50683 scanned packages
  run `npm audit fix` to fix 13 of them.
  139 vulnerabilities require semver-major dependency updates.
  1 vulnerability requires manual review. See the full report for details.
```

IMO, for identity verification package it is very bad to have 20 high risk vulnerabilities.

## After running `npm audit fix` (without force)
```
added 1921 packages from 951 contributors in 60.674s
fixed 13 of 153 vulnerabilities in 50683 scanned packages
  1 vulnerability required manual review and could not be updated
  3 package updates for 139 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
```
### `npm audit`
```
found 128 vulnerabilities (124 low, 1 moderate, 3 high) in 50671 scanned packages
  127 vulnerabilities require semver-major dependency updates.
  1 vulnerability requires manual review. See the full report for details.
```
### **Simple check shows that `npm run dev` and `npm run test` still works fine**

and the only `package.json` change was `surge@^0.20.1 --> ^0.20.4`

<details><summary>npm outdated</summary>

<pre>
Package                                              Current          Wanted  Latest  Location
@babel/cli                                             7.1.2           7.4.4   7.4.4  onfido-sdk-ui
@babel/core                                            7.1.2           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-proposal-class-properties                7.1.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-proposal-decorators                      7.1.2           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-proposal-export-default-from             7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-export-namespace-from           7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-function-sent                   7.1.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-json-strings                    7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-numeric-separator               7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-throw-expressions               7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-syntax-dynamic-import                    7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-syntax-import-meta                       7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-transform-flow-strip-types               7.0.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-transform-react-jsx                      7.0.0           7.3.0   7.3.0  onfido-sdk-ui
@babel/plugin-transform-runtime                   7.0.0-rc.3           7.4.4   7.4.4  onfido-sdk-ui
@babel/preset-env                                      7.1.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/register                                        7.0.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/runtime-corejs2                            7.0.0-rc.3           7.4.4   7.4.4  onfido-sdk-ui
autoprefixer                                           7.2.3           7.2.6   9.5.1  onfido-sdk-ui
babel-core                                    7.0.0-bridge.0  7.0.0-bridge.0  6.26.3  onfido-sdk-ui
babel-loader                                           8.0.4           8.0.5   8.0.5  onfido-sdk-ui
babel-upgrade                                         0.0.23          0.0.23   1.0.1  onfido-sdk-ui
blueimp-load-image                                    2.12.2          2.12.2  2.21.0  onfido-sdk-ui
classnames                                             2.2.5           2.2.5   2.2.6  onfido-sdk-ui
css-loader                                             2.1.0           2.1.1   2.1.1  onfido-sdk-ui
eslint                                                5.14.1          5.16.0  5.16.0  onfido-sdk-ui
eslint-plugin-flowtype                                 3.4.2           3.7.0   3.7.0  onfido-sdk-ui
eslint-plugin-react                                   7.12.4          7.13.0  7.13.0  onfido-sdk-ui
eventemitter2                                          2.1.3           2.1.3   5.0.1  onfido-sdk-ui
file-loader                                            0.9.0           0.9.0   3.0.1  onfido-sdk-ui
flow-bin                                              0.93.0          0.93.0  0.98.0  onfido-sdk-ui
history                                                4.5.1           4.5.1   4.9.0  onfido-sdk-ui
http-server                                           0.10.0          0.10.0  0.11.1  onfido-sdk-ui
jest                                                  23.6.0          23.6.0  24.7.1  onfido-sdk-ui
jest-cli                                              23.6.0          23.6.0  24.7.1  onfido-sdk-ui
less-loader                                            4.0.5           4.1.0   5.0.0  onfido-sdk-ui
mini-css-extract-plugin                                0.5.0           0.5.0   0.6.0  onfido-sdk-ui
node-polyglot                                          2.2.2           2.3.0   2.3.0  onfido-sdk-ui
pdfobject                                      2.0.201604172   2.0.201604172   2.1.1  onfido-sdk-ui
postcss-base64                                         0.4.1           0.4.1   0.7.1  onfido-sdk-ui
postcss-custom-media                                   5.0.1           5.0.1   7.0.8  onfido-sdk-ui
postcss-loader                                         2.0.9           2.1.6   3.0.0  onfido-sdk-ui
postcss-url                                            7.3.0           7.3.2   8.0.0  onfido-sdk-ui
preact-compat                                         3.18.4          3.18.5  3.18.5  onfido-sdk-ui
react-modal-onfido                                     1.5.2           1.5.2   1.5.3  onfido-sdk-ui
react-native-listener                                  1.0.1           1.0.1   1.0.2  onfido-sdk-ui
react-phone-number-input                              0.15.2          0.15.2  2.3.11  onfido-sdk-ui
react-redux                                            4.4.6           4.4.6   7.0.3  onfido-sdk-ui
react-webcam-onfido                                   0.1.10          0.1.12  0.1.12  onfido-sdk-ui
redux                                                  3.5.2           3.5.2   4.0.1  onfido-sdk-ui
regenerator-runtime                                   0.12.1          0.12.1  0.13.2  onfido-sdk-ui
reselect                                               2.5.1           2.5.1   4.0.0  onfido-sdk-ui
rimraf                                                 2.6.2           2.6.3   2.6.3  onfido-sdk-ui
socket.io-client                                       2.0.4           2.2.0   2.2.0  onfido-sdk-ui
source-map-loader                                      0.1.6           0.1.6   0.2.4  onfido-sdk-ui
speed-measure-webpack-plugin                           1.3.0           1.3.1   1.3.1  onfido-sdk-ui
supports-webp                                          1.0.3           1.0.3   2.0.1  onfido-sdk-ui
terser-webpack-plugin                                  1.2.2           1.2.3   1.2.3  onfido-sdk-ui
visibilityjs                                           1.2.4           1.2.4   2.0.2  onfido-sdk-ui
webpack                                               4.29.5          4.30.0  4.30.0  onfido-sdk-ui
webpack-bundle-analyzer                               2.11.1          2.13.1   3.3.2  onfido-sdk-ui
webpack-cli                                            3.2.3           3.3.1   3.3.1  onfido-sdk-ui
webpack-dev-server                                     3.2.0           3.3.1   3.3.1  onfido-sdk-ui
wpt                                                   5.1.19             git     git  onfido-sdk-ui
</pre>

</details>

## After running `npm audit fix --force`
```
added 194 packages from 107 contributors, removed 121 packages, updated 116 packages and moved 18 packages in 30.946s
fixed 127 of 128 vulnerabilities in 50671 scanned packages
  1 vulnerability required manual review and could not be updated
  3 package updates for 127 vulns involved breaking changes
  (installed due to `--force` option)
```
### `npm audit`
```
found 1 high severity vulnerability in 1716243 scanned packages
  1 vulnerability requires manual review. See the full report for details.
```
### **Simple check shows that `npm run dev` and `npm run test` still works fine**

`package.json` changes
```
jest@^23.6.0 --> ^24.7.1
jest-cli@^23.6.0 --> ^24.7.1
webpack-bundle-analyzer@^2.11.1 --> ^3.3.2
```

<details><summary>npm outdated</summary>

<pre>
Package                                              Current          Wanted  Latest  Location
@babel/cli                                             7.1.2           7.4.4   7.4.4  onfido-sdk-ui
@babel/core                                            7.1.2           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-proposal-class-properties                7.1.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-proposal-decorators                      7.1.2           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-proposal-export-default-from             7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-export-namespace-from           7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-function-sent                   7.1.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-json-strings                    7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-numeric-separator               7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-proposal-throw-expressions               7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-syntax-dynamic-import                    7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-syntax-import-meta                       7.0.0           7.2.0   7.2.0  onfido-sdk-ui
@babel/plugin-transform-flow-strip-types               7.0.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/plugin-transform-react-jsx                      7.0.0           7.3.0   7.3.0  onfido-sdk-ui
@babel/plugin-transform-runtime                   7.0.0-rc.3           7.4.4   7.4.4  onfido-sdk-ui
@babel/preset-env                                      7.1.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/register                                        7.0.0           7.4.4   7.4.4  onfido-sdk-ui
@babel/runtime-corejs2                            7.0.0-rc.3           7.4.4   7.4.4  onfido-sdk-ui
autoprefixer                                           7.2.3           7.2.6   9.5.1  onfido-sdk-ui
babel-core                                    7.0.0-bridge.0  7.0.0-bridge.0  6.26.3  onfido-sdk-ui
babel-loader                                           8.0.4           8.0.5   8.0.5  onfido-sdk-ui
babel-upgrade                                         0.0.23          0.0.23   1.0.1  onfido-sdk-ui
blueimp-load-image                                    2.12.2          2.12.2  2.21.0  onfido-sdk-ui
classnames                                             2.2.5           2.2.5   2.2.6  onfido-sdk-ui
css-loader                                             2.1.0           2.1.1   2.1.1  onfido-sdk-ui
eslint                                                5.14.1          5.16.0  5.16.0  onfido-sdk-ui
eslint-plugin-flowtype                                 3.4.2           3.7.0   3.7.0  onfido-sdk-ui
eslint-plugin-react                                   7.12.4          7.13.0  7.13.0  onfido-sdk-ui
eventemitter2                                          2.1.3           2.1.3   5.0.1  onfido-sdk-ui
file-loader                                            0.9.0           0.9.0   3.0.1  onfido-sdk-ui
flow-bin                                              0.93.0          0.93.0  0.98.0  onfido-sdk-ui
history                                                4.5.1           4.5.1   4.9.0  onfido-sdk-ui
http-server                                           0.10.0          0.10.0  0.11.1  onfido-sdk-ui
less-loader                                            4.0.5           4.1.0   5.0.0  onfido-sdk-ui
mini-css-extract-plugin                                0.5.0           0.5.0   0.6.0  onfido-sdk-ui
node-polyglot                                          2.2.2           2.3.0   2.3.0  onfido-sdk-ui
pdfobject                                      2.0.201604172   2.0.201604172   2.1.1  onfido-sdk-ui
postcss-base64                                         0.4.1           0.4.1   0.7.1  onfido-sdk-ui
postcss-custom-media                                   5.0.1           5.0.1   7.0.8  onfido-sdk-ui
postcss-loader                                         2.0.9           2.1.6   3.0.0  onfido-sdk-ui
postcss-url                                            7.3.0           7.3.2   8.0.0  onfido-sdk-ui
preact-compat                                         3.18.4          3.18.5  3.18.5  onfido-sdk-ui
react-modal-onfido                                     1.5.2           1.5.2   1.5.3  onfido-sdk-ui
react-native-listener                                  1.0.1           1.0.1   1.0.2  onfido-sdk-ui
react-phone-number-input                              0.15.2          0.15.2  2.3.11  onfido-sdk-ui
react-redux                                            4.4.6           4.4.6   7.0.3  onfido-sdk-ui
react-webcam-onfido                                   0.1.10          0.1.12  0.1.12  onfido-sdk-ui
redux                                                  3.5.2           3.5.2   4.0.1  onfido-sdk-ui
regenerator-runtime                                   0.12.1          0.12.1  0.13.2  onfido-sdk-ui
reselect                                               2.5.1           2.5.1   4.0.0  onfido-sdk-ui
rimraf                                                 2.6.2           2.6.3   2.6.3  onfido-sdk-ui
socket.io-client                                       2.0.4           2.2.0   2.2.0  onfido-sdk-ui
source-map-loader                                      0.1.6           0.1.6   0.2.4  onfido-sdk-ui
speed-measure-webpack-plugin                           1.3.0           1.3.1   1.3.1  onfido-sdk-ui
supports-webp                                          1.0.3           1.0.3   2.0.1  onfido-sdk-ui
terser-webpack-plugin                                  1.2.2           1.2.3   1.2.3  onfido-sdk-ui
visibilityjs                                           1.2.4           1.2.4   2.0.2  onfido-sdk-ui
webpack                                               4.29.5          4.30.0  4.30.0  onfido-sdk-ui
webpack-cli                                            3.2.3           3.3.1   3.3.1  onfido-sdk-ui
webpack-dev-server                                     3.2.0           3.3.1   3.3.1  onfido-sdk-ui
wpt                                                   5.1.19             git     git  onfido-sdk-ui
</pre>
</details>

## `ecstatic`'s high severity vulnerability
This one is tricky though. Yesterday owner of this package unpublished all (really) versions from npm because of vulnerability. And although you can still fix vulnerability on your side by upgrading that one package in your `package-lock.json` manually, it's not a solution.
Currently there is [an open issue](https://github.com/jfhbrook/node-ecstatic/issues/255) on their side to provide version for at least ^3.x.x so that ppl will be able to install `http-server`. also there is [an open issue](https://github.com/indexzero/http-server/issues/521) on their side too.

So for that one you should wait. Oooor change the package to some other static server for Travis (seems like you are using it for Travis only).

### `npm run dev` runs but page has errors because of `redux`. some minor changes to codebase.

<details><summary>npm outdated</summary>

<pre>
Package                          Current          Wanted  Latest  Location
autoprefixer                       7.2.6           7.2.6   9.5.1  onfido-sdk-ui
babel-core                7.0.0-bridge.0  7.0.0-bridge.0  6.26.3  onfido-sdk-ui
babel-upgrade                     0.0.23          0.0.23   1.0.1  onfido-sdk-ui
blueimp-load-image                2.12.2          2.12.2  2.21.0  onfido-sdk-ui
classnames                         2.2.5           2.2.5   2.2.6  onfido-sdk-ui
eventemitter2                      2.1.3           2.1.3   5.0.1  onfido-sdk-ui
file-loader                        0.9.0           0.9.0   3.0.1  onfido-sdk-ui
flow-bin                          0.93.0          0.93.0  0.98.0  onfido-sdk-ui
history                            4.5.1           4.5.1   4.9.0  onfido-sdk-ui
http-server                       0.10.0          0.10.0  0.11.1  onfido-sdk-ui
less-loader                        4.1.0           4.1.0   5.0.0  onfido-sdk-ui
mini-css-extract-plugin            0.5.0           0.5.0   0.6.0  onfido-sdk-ui
pdfobject                  2.0.201604172   2.0.201604172   2.1.1  onfido-sdk-ui
postcss-base64                     0.4.1           0.4.1   0.7.1  onfido-sdk-ui
postcss-custom-media               5.0.1           5.0.1   7.0.8  onfido-sdk-ui
postcss-loader                     2.1.6           2.1.6   3.0.0  onfido-sdk-ui
postcss-url                        7.3.2           7.3.2   8.0.0  onfido-sdk-ui
react-modal-onfido                 1.5.2           1.5.2   1.5.3  onfido-sdk-ui
react-native-listener              1.0.1           1.0.1   1.0.2  onfido-sdk-ui
react-phone-number-input          0.15.2          0.15.2  2.3.11  onfido-sdk-ui
react-redux                        4.4.6           4.4.6   7.0.3  onfido-sdk-ui
redux                              3.5.2           3.5.2   4.0.1  onfido-sdk-ui
regenerator-runtime               0.12.1          0.12.1  0.13.2  onfido-sdk-ui
reselect                           2.5.1           2.5.1   4.0.0  onfido-sdk-ui
source-map-loader                  0.1.6           0.1.6   0.2.4  onfido-sdk-ui
supports-webp                      1.0.3           1.0.3   2.0.1  onfido-sdk-ui
visibilityjs                       1.2.4           1.2.4   2.0.2  onfido-sdk-ui
wpt                               5.1.19             git     git  onfido-sdk-ui
</pre>
</details>

Of course you can also update all major versions and keep updating packages once in a while when you bump major version of package (and seems like you do it often)

## Why? why you haven't spotted this (maybe you did, maybe not)
`npm install` automatically does `npm audit` so you should have been able to see these warnings already. But the tool that you are using `Snyk` which is integrated to this repository is not checking lock files. :( so it sees, for ex., `@babel/core@^7.1.2` and it checks with fresh version of that package instead of checking locked version. Thats why all your pull request are "ok", but in reality they are not.

## Conclusion
Always keep your dependencies up to date and try to keep their count to as small as you can.

p.s. `wpt` is installed and pinned to specific version via Github tag instead of package. I am not here to judge, but probably it make sense to use their package via npm instead.

### PR DESCRIPTION
**Pull request by davityavryan**
# Problem
Resolves #646 and #656

# Solution
Instead of using git clone I have changed it to use tar package with same version

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [ ] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [ ] Have new automated tests been implemented?
- [ ] Have new manual tests been written down?
- [x] Have tests passed locally?
- [ ] Have any new strings been translated?

### CODE REVIEW

**Comment by davityavryan** [comment]
Seems like build failure is not related to my changes. 🙃

**Comment by bartzet** [comment]
Hi @davityavryan I'm not sure why this is failing but all our other builds are green.

**Comment by davityavryan** [comment]
@bartzet the issue is related to [`openssl`](https://travis-ci.org/onfido/onfido-sdk-ui/jobs/538732978#L478) so I assume either you had some problem in `master` branch or it was just a build "hick-up".

I can also see that my branch is out of date with `development` but I have rebased on top of `master`. If you do merge all your PRs to `development` and then create a release by merging to `master` then I will update it. Can you confirm this?

**Comment by bartzet** [comment]
hi @davityavryan I got more info on that, it turns out the PRs that are opened by someone outside of the Onfido organization will always fail.

We will get some 👁 on this and merge if 👌

**Comment by davityavryan** [comment]
@bartzet oh. Yes it's 👌. 
Thanks for clarification.

**Comment by davityavryan** [comment]
@bartzet any news about this? any ETA?

**Comment by stefaniacardenas** [comment]
Hi @davityavryan, thanks for your contribution. I will now merge your PR into a feature branch where we can test the changes before merging to `development`. We will try to include this change in the next release. Again, thank you very much for taking the time to contribute.

**Pull request merged**
