### PR TITLE
Post release/merge 6 4 0 to development

### PR DESCRIPTION
**Pull request by kopijunkie**
# Task

- Merge `master` including `release/6.4.0` into `development`
- Update `RELEASE_GUIDELINES` documentation for git commands to run post release for this step

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1281-pr-onfido-sdk-ui-onfido.surge.sh

**Review by ethan605 — APPROVED** [review]
LGTM!

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1281-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1281-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
