### PR TITLE
Bug/client ie issue

### PR DESCRIPTION
**Pull request by stefaniacardenas**
This PR fixes a regression where cross device client not working on IE11 due to missing polyfill for URLSearchParams.

cc @seewah

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-275-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-275-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://275-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by hjheath** [comment]
Code looks good.

The polyfill adds 1.7kb to the SDK and is only used by test code - specifically so we can test the cross device flow easily on IE 11. The question is whether we are OK with that tradeoff. My opinion is that it's fine - @rfreitas what do you think?

**Comment by rfreitas** [comment]
okay for now. we can create a tech debt issue for it though.

**Comment by stefaniacardenas** [comment]
Issue [here](https://jira.onfido.co.uk/browse/CX-1552)

**Pull request merged**
