### PR TITLE
Don't show x-device button if on `mobileFlow` on a desktop

### PR DESCRIPTION
**Pull request by kopijunkie**
# Problem
For `test` Node environment, e.g. the `development` Surge link, the error message displayed when a user tries to open the x-device link on a desktop browser does not get displayed.

# Solution
Add a check to only display the "Continue on phone" button if user is not already on the x-device mobile flow.

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [ ] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [ ] Have new automated tests been implemented?
- [ ] Have new manual tests been written down?
- [ ] Have any new strings been translated?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-879-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-879-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://879-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-879-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-879-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://879-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by bartzet** [comment]
Would we be able to add the check to the existing 2 tests:
`should succesfully complete cross device e2e flow with document and selfie upload`
&
`should succesfully complete cross device e2e flow with selfie upload` to `crossDeviceSubmit` steps that this button is not Displayed?

**Comment by kopijunkie** [comment]
> Would we be able to add the check to the existing 2 tests:
> `should succesfully complete cross device e2e flow with document and selfie upload`
> &
> `should succesfully complete cross device e2e flow with selfie upload` to `crossDeviceSubmit` steps that this button is not Displayed?

I was unable to reproduce the scenario where the expected error screen did not display on my local dev environment and it also does not happen on prod environment. So the test would always fail locally. I think it would be better to add a test for the error screen if there isn't one already.

**Comment by bartzet** [comment]
Please correct me if I'm wrong but I was thinking to add the test that checks if the `Continue on phone` button is not visible as currently on `https://development-branch-onfido-sdk-ui-onfido.surge.sh/` it does. I wasn't able to reproduce the scenario with the error screen neither.  

image

**Comment by kopijunkie** [comment]
> Please correct me if I'm wrong but I was thinking to add the test that checks if the `Continue on phone` button is not visible as currently on `https://development-branch-onfido-sdk-ui-onfido.surge.sh/` it does. I wasn't able to reproduce the scenario with the error screen neither.
> 
> image

The button will still be visible on `https://development-branch-onfido-sdk-ui-onfido.surge.sh/` until the PR gets merged in tbh. But it won't be visible on https://879-pr-onfido-sdk-ui-onfido.surge.sh/ and with the release/staging links on this PR you will get the error screen.

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-879-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-879-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://879-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
