### PR TITLE
Post release/merge 6 0 0 into development

### PR DESCRIPTION
**Pull request by stefaniacardenas**
# Task
Merge `master` including `release/6.0.0` into `development`

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1191-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1191-pr-onfido-sdk-ui-onfido.surge.sh

**Review by ethan605 — APPROVED** [review]

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1191-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1191-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
