### PR TITLE
Artificial time wait interval on non safari browsers

### PR DESCRIPTION
**Pull request by kopijunkie**
# Problem
As raised in #1001 on non-Safari browsers there is a slight delay of about 2000ms before the Document Capture screen gets rendered due to the workaround for the Safari 13.1 bug.

# Solution
Make an initial call of `this.checkCameraSupport` in `withCameraDetection` regardless of browser to prevent 2000ms delay.

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [x] Has the CHANGELOG been updated?
- [ ] Has the README been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [ ] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1002-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1002-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1002-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1002-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1002-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1002-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by aoumiri** [comment]
Thanks a lot!

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1002-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1002-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1002-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
