### PR TITLE
Do not merge - Applause/2018 10 15

### PR DESCRIPTION
**Pull request by stefaniacardenas**
# Task

Applause cycle 2018 10 15

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-491-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-491-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://491-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by bartzet** [comment]
@stefaniacardenas shall we close this PR since the cycle is finished?

**Pull request merged**
