### PR TITLE
Fixed Spanish translations

### PR DESCRIPTION
**Pull request by stefaniacardenas**
# Problem
Some Spanish sentences include grammatical errors or are incorrect.

# Solution
Fix grammar and syntax errors

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [n/a] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [n/a] Have new automated tests been implemented?
- [n/a] Have new manual tests been written down?
- [x] Have tests passed locally?
- [x] Have any new strings been translated?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-516-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-516-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://516-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-516-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-516-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://516-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by josokinas** [comment]
P.S. Have no idea - don't speak Spanish 😆

**Comment by rfreitas** [comment]
Travis automatic deployment: https://516-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-516-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
