### PR TITLE
Update sms sent icon to look less like an error

### PR DESCRIPTION
**Pull request by hjheath**

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-266-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://266-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by stefaniacardenas** [comment]
I just noticed that the icon has some white margin at the top which the example screen on Jira doesn't have. I don't think it's due to svg optimisation, I guess this is a question for @danielspagnolo 
here are the screenshots
Icon within the example screen on Jira
screen shot 2017-11-22 at 11 12 09
Detail of icon provided
screen shot 2017-11-22 at 11 12 57

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-266-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://266-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by danielspagnolo** [comment]
@stefaniacardenas We have a ticket to fix the icon issue CX-1318. I am aware of it and it's related to how sketch exports SVGs :)

**Pull request merged**
