### PR TITLE
Fix document selector long line

### PR DESCRIPTION
**Pull request by elhesuu**
# Problem
In PoA document selection, long lines are not breaking on IE11, breaking the layout.

image

# Solution
Set `flex-basis: 100%` on flex children

image

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [n/a] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [n/a] Have new automated tests been implemented?
- [n/a] Have new manual tests been written down?
- [n/a] Have tests passed locally?
- [n/a] Have any new strings been translated?

### CODE REVIEW

**Comment by elhesuu** [comment]
Depends on https://github.com/onfido/onfido-sdk-ui/pull/439

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-441-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-441-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-441-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-441-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by seewah** [comment]
screen shot 2018-09-06 at 15 41 11

problem still persists on IE 11, @elhesuu

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-441-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://441-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by elhesuu** [comment]
Thanks @seewah. Just updated it too

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-441-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-441-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://441-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
