### PR TITLE
Remove step from PR template

### PR DESCRIPTION
**Pull request by bartzet**
# Problem
We don't need this step from the PR template

# Solution
Remove the step

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [ ] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [ ] Have new automated tests been implemented?
- [ ] Have new manual tests been written down?
- [ ] Have tests passed locally?
- [ ] Have any new strings been translated?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-749-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://749-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-749-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by bartzet** [comment]
Relevant JIRA task - CX-1972 - was created more than 1 year ago. @rfreitas do you remember what was the motivation for it?

I'm ok with keeping it tbh. Maybe we could specify it that we mean automated tests here?

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-749-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-749-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://749-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-749-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-749-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://749-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
well, don't tests run on CI? checklist should be for stuff that the CI won't catch IMO

**Comment by kopijunkie** [comment]
> well, don't tests run on CI? checklist should be for stuff that the CI won't catch IMO

That is true. I was thinking in terms of making sure nothing (including new automated tests) has failed locally before creating the PR since it would fail on CI for sure.

**Comment by bartzet** [comment]
Merging myself, as Gokhan accepted that PR but he doesn't have access to that repo yet.

**Pull request merged**
