### PR TITLE
Do not merge / PoA documents tweaks

### PR DESCRIPTION
**Pull request by elhesuu**
# Problem
- doc selection benefits letter copy should be "Government authorised household benefits eg. Jobseeker allowance, Housing benefit, Tax credits"
- Guidance page should see "Issue date or Summary period" instead of "Issue date or Summary dates"
- Council tax letters should appear above Benefits letters

# Solution
Update translations and document types config object 

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [n/a] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [n/a] Have new automated tests been implemented?
- [n/a] Have new manual tests been written down?
- [ ] Have tests passed locally?
- [n/a] Have any new strings been translated?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-461-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-461-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://461-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by seewah** [comment]
screen shot 2018-09-21 at 11 45 13
please change Summary dates to Summary period :)

**Comment by elhesuu** [comment]
Closing in favour of #469

**Pull request closed without merging**
