### PR TITLE
Make README description of shape of onComplete() argument more accurate

### PR DESCRIPTION
**Pull request by davidpcaldwell**
# Problem
The `document_back` property in the `onComplete()` callback is not documented.

# Solution
Add it to example argument in the README.

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [X] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [n/a] Have new automated tests been implemented?
- [n/a] Have new manual tests been written down?
- [n/a] Have tests passed locally?
- [n/a] Have any new strings been translated?

### CODE REVIEW

**Comment by seewah** [comment]
thanks for the PR. The only problem with this example is that he "back" of a passport does not make much sense (we only take one image, which is the photo page). So we should either change the document type to a card-type document with 2 sides, or leave it as it is.

**Comment by davidpcaldwell** [comment]
Or perhaps provide multiple examples, or somewhere in the description provide information about the `document_back` property?

**Comment by davidpcaldwell** [comment]
Added another commit; see what you think of this wording.

**Comment by davidpcaldwell** [comment]
Whoops, added one more commit to remove some duplication.

**Comment by davidpcaldwell** [comment]
Whoops, one more to replace `passport` with `driving_licence` ...

**Comment by stefaniacardenas** [comment]
Thank you for your contribution @davidpcaldwell. I will merge this PR into a branch so that the CI can run properly and we can make any changes if needed. We will include your contribution in the next release.  Many thanks.

**Pull request merged**
