### PR TITLE
Remove element level selector for anchor links

### LINKED ISSUE #1391: CSS problems after the version 6.7.0
Hey guys, we're using this SDK on our React project. We have no problem until your latest build. It breaks our css. You can see the related css below.

````
a, .onfido-sdk-ui-Theme-link, .onfido-sdk-ui-Theme-textButton {
    font-family: var(--osdk-font-family-body);
    text-decoration: none;
    border: 1px solid transparent;
    /* border-bottom-color: var(--osdk-color-border-link-underline); */
    background-color: transparent;
    color: var(--osdk-color-content-body);
}

a:not(:disabled):hover, .onfido-sdk-ui-Theme-link:not(:disabled):hover, .onfido-sdk-ui-Theme-textButton:not(:disabled):hover {
    background-color: var(--osdk-color-background-link-hover);
    color: var(--osdk-color-content-link-text-hover);
}
````

Since the "a" tag's CSS is used directly in this way, it affects globally.

I've seen these two so far, I don't know if anything else like these. 

For now, we're using version 6.6.0.

### Version info:

- Onfido SDK: 6.7.0
- OS: macOS 11.0.1
- Browser: Chrome
- Node: 10.14.2
- Npm: 7.7.5

An example:
Mar-26-2021 12-45-45

### PR DESCRIPTION
**Pull request by kopijunkie**
# Problem
The link customisation option implementation in release 6.7.0 included anchor link element level selectors which is now overriding host apps/sites' styles

Fixes #1391 

# Solution
Remove element level selectors from SDK stylesheet(s)

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [x] Has the CHANGELOG been updated?
- [ ] Has the README been updated?
- [ ] Has the CONTRIBUTING doc been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [ ] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1392-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1392-pr-onfido-sdk-ui-onfido.surge.sh

**Review by stefaniacardenas — COMMENTED** [review]
Looks good to me. Is it the only place where tags are styled directly?

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1392-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by kopijunkie** [comment]
> Looks good to me. Is it the only place where tags are styled directly?

Yeah. Had a look through the stylesheets & this stylesheet/links is the only one where there is a top-level element selector. 

There are some in `src/components/Spinner/style.scss`, `src/components/PhoneNumberInput/style.scss` but they are within a class `.inner > div`, `.phoneNumberContainer > button`, `.phoneNumberContainer > input`.

**Review by stefaniacardenas — APPROVED** [review]

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1392-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1392-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1392-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1392-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1392-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1392-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
