### PR TITLE
Update dev urls

### PR DESCRIPTION
**Pull request by joninvski**
# Problem
With our k8s cluster update we now have new urls in dev.

# Solution
This commit updates the urls to the new format.

## Checklist
_put `n/a` if item is not relevant to PR changes_

- [NA] Have the CHANGELOG, README, MIGRATION, RELEASE_GUIDELINES docs been updated?
- [NA] Have new automated tests been implemented?
- [NA] Have new manual tests been written down?
- [NA] Have tests passed locally?
- [NA ] Have any new strings been translated?

### CODE REVIEW

**Comment by joninvski** [comment]
Please do not merge, as i'm still missing the token-factory update.

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by joninvski** [comment]
The `sdk-token-factory` domain name is now working, i think we can remove the `do-not-merge` label.

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://663-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-663-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
