### PR TITLE
Release/6.0.0

### PR DESCRIPTION
**Pull request by stefaniacardenas**
### Added

- UI: Add country selection screen after document selection. This screen is skipped by default for a preselected document but can still be displayed by enabling the `showCountrySelection` option for the `document` step.
- UI: New warnings for cut-off & blurry images detection.
- UI: When the uploaded image is either cut-off, glary or blurry, the end-user must retry at most 2 times prior to proceeding further.
- Internal: The release script and the `release/RELEASE_GUIDELINE.md` file now include the information needed to update the `MIGRATION.md` file.
- UI: Added Residence Permit option for document selection

### Changed

- Internal: Changed resolution constraints for live document captures from `720` to `1080`.
- Public: Remove `SMS_BODY` key from locale files as it's not a customisable key and does not belong to this codebase.

### Fixed

- Public: Return a generic error for unmapped Onfido API validation keys.
- Fix typo in PhoneNumberInput SASS styles producing invalid CSS
- UI: Fixed inconsistent font family for non Primary, Secondary button elements.

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1189-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1189-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1189-pr-onfido-sdk-ui-onfido.surge.sh

**Review by kopijunkie — APPROVED** [review]

**Review by ethan605 — APPROVED** [review]
LGTM!

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1189-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1189-pr-onfido-sdk-ui-onfido.surge.sh

**Pull request merged**
