### PR TITLE
Release/6.3.1

### PR DESCRIPTION
**Pull request by kopijunkie**
### Fixed

- Public: Fix missing country selector screen when the SDK is imported as an NPM module.

### CODE REVIEW

**Comment by rfreitas** [comment]
Travis automatic deployment: https://staging-1266-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://release-1266-pr-onfido-sdk-ui-onfido.surge.sh

**Comment by rfreitas** [comment]
Travis automatic deployment: https://1266-pr-onfido-sdk-ui-onfido.surge.sh

**Review by ethan605 — APPROVED** [review]
LGTM!

**Pull request merged**
